### ISSUE TITLE
`helm repo add` proxy+webpack doesn't work on travis

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1947]
For command: `helm repo add bitnami https://charts.bitnami.com/bitnami`, I got the error as followed:

> Error: Couldn’t load repositories file (.helm/repository/repositories.yaml). You might need to run `helm init` (or `helm init --client-only` if tiller is already installed.

https://travis.ibm.com/composer/kui/jobs/18715172#L3146

**Comment by starpit** [comment]
this should be resolved by #1952

**Comment by myan9** [comment]
`helm repo add` still doesn't work on travis, with the same error message:
https://travis.ibm.com/composer/kui/jobs/19366134#L3339-L3342

**Comment by starpit** [comment]
you mean for webpack+proxy? it should work with electron?

**Comment by myan9** [comment]
yes, for webpack+proxy

**Comment by starpit** [comment]
i guess the tests are assuming that `helm init` has been run. this seems like a gap

**Comment by myan9** [comment]
helm proxy test doesn't  work on travis, but locally its good.

test helm-repo-add-and-search locally
![Screen Shot 2019-08-06 at 11 49 02 AM](https://user-images.githubusercontent.com/21212160/62555031-34841580-b840-11e9-8d16-60246fefc422.png)
